// THIS FILE GENERATED BY CodeX: frontend/src/components/Select.jsx
import React from "react";

const Select = ({
  label,
  options = [],
  value,
  onChange,
  multiple = false,
  placeholder = "Chọn...",
  error,
  className = "",
  ...props
}) => {
  const handleChange = (event) => {
    if (!onChange) return;
    if (multiple) {
      const selectedValues = Array.from(event.target.selectedOptions).map(
        (opt) => opt.value
      );
      onChange(selectedValues);
    } else {
      onChange(event.target.value);
    }
  };

  return (
    <label className={`field ${className}`.trim()}>
      {label && <span className="field-label">{label}</span>}
      <select
        className={`field-input ${error ? "has-error" : ""}`}
        multiple={multiple}
        value={value}
        onChange={handleChange}
        {...props}
      >
        {!multiple && (
          <option value="" disabled>
            {placeholder}
          </option>
        )}
        {options.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
      {error && <span className="field-error">{error}</span>}
      {multiple && (
        <span className="field-hint">Giữ Ctrl/Cmd để chọn nhiều</span>
      )}
    </label>
  );
};

export default Select;
