// THIS FILE GENERATED BY CodeX: frontend/src/services/storyService.js
import api from "./api";

const storyService = {
  createStory: (formData) =>
    api.post("/api/stories", formData, {
      headers: { "Content-Type": "multipart/form-data" },
    }),

  getStory: (storyId) => api.get(`/api/stories/${storyId}`),

  createVolume: (storyId, payload) =>
    api.post(`/api/stories/${storyId}/volumes`, payload),

  createChapter: (storyId, volumeId, payload) =>
    api.post(`/api/stories/${storyId}/volumes/${volumeId}/chapters`, payload),

  getChapterContent: (storyId, chapterId) =>
    api.get(`/api/stories/${storyId}/chapters/${chapterId}/content`),

  getTags: async () => {
    try {
      return await api.get("/api/tags");
    } catch (error) {
      // Fallback for legacy tag endpoint.
      return api.get("/api/v1/tags");
    }
  },
};

export default storyService;
