// THIS FILE GENERATED BY CodeX: frontend/src/layouts/Footer.jsx
import React from "react";

const Footer = () => {
  return (
    <footer
      className="app-footer"
      style={{ backgroundColor: "#2f3b4a", color: "#fff", padding: "16px 0" }}
    >
      <div className="container">
        <p>© 2026 WebTruyen. Bản quyền thuộc về WebTruyen.</p>
      </div>
    </footer>
  );
};

export default Footer;
