// THIS FILE GENERATED BY CodeX: frontend/src/layouts/Header.jsx
import React from "react";
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <header
      className="app-header"
      style={{ backgroundColor: "#5b2d2a", color: "#fff" }}
    >
      <div className="container header-inner">
        <Link to="/author/create-story" className="brand" style={{ color: "#fff" }}>
          WebTruyen Author
        </Link>
        <nav className="nav-links" style={{ display: "flex", gap: "16px" }}>
          <Link to="/author/create-story" style={{ color: "#fff" }}>
            Tạo truyện
          </Link>
          <a href="#" style={{ color: "#fff" }}>
            Truyện của tôi
          </a>
        </nav>
      </div>
    </header>
  );
};

export default Header;
