// THIS FILE GENERATED BY CodeX: frontend/src/pages/Author/CreateVolume.jsx
import React, { useState } from "react";
import Button from "../../components/Button";
import Input from "../../components/Input";
import storyService from "../../services/storyService";
import useNotify from "../../hooks/useNotify";

const CreateVolume = ({ storyId, onCreated, onCancel }) => {
  const { notify } = useNotify();
  const [title, setTitle] = useState("");
  const [sequenceIndex, setSequenceIndex] = useState(1);
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const [createdVolumeId, setCreatedVolumeId] = useState("");

  const validate = () => {
    const nextErrors = {};
    if (!title.trim()) nextErrors.title = "Tiêu đề volume là bắt buộc";
    return nextErrors;
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    const nextErrors = validate();
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) return;
    try {
      setLoading(true);
      const payload = {
        title: title.trim(),
        sequenceIndex: Number(sequenceIndex) || 1,
      };
      const response = await storyService.createVolume(storyId, payload);
      const volumeId = response?.data?.id || response?.data?.volumeId;
      setCreatedVolumeId(volumeId ? String(volumeId) : "");
      notify("Tạo volume thành công", "success");
      onCreated?.(volumeId || response?.data);
    } catch (error) {
      console.error("createVolume error", error);
      notify("Không thể tạo volume. Vui lòng thử lại.", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form className="card form" onSubmit={handleSubmit}>
      <h3>Tạo Volume</h3>
      <Input
        label="Tiêu đề Volume"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        error={errors.title}
        placeholder="Nhập tiêu đề volume"
      />
      <Input
        label="Thứ tự"
        type="number"
        min="1"
        value={sequenceIndex}
        onChange={(e) => setSequenceIndex(e.target.value)}
      />
      <div className="form-actions">
        <Button type="submit" loading={loading}>
          Lưu Volume
        </Button>
        {onCancel && (
          <Button type="button" variant="ghost" onClick={onCancel}>
            Hủy
          </Button>
        )}
      </div>
      {createdVolumeId && (
        <div className="field-hint">
          <a
            href={`/author/stories/${storyId}/volumes/${createdVolumeId}/create-chapter`}
          >
            Đi tới tạo Chapter
          </a>
        </div>
      )}
    </form>
  );
};

export default CreateVolume;
