// THIS FILE GENERATED BY CodeX: frontend/src/pages/Author/CreateStory.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Button from "../../components/Button";
import FileUpload from "../../components/FileUpload";
import Input from "../../components/Input";
import Select from "../../components/Select";
import useNotify from "../../hooks/useNotify";
import storyService from "../../services/storyService";

const CreateStory = () => {
  const navigate = useNavigate();
  const { notify } = useNotify();
  const [title, setTitle] = useState("");
  const [summary, setSummary] = useState("");
  const [visibility, setVisibility] = useState("DRAFT");
  const [categoryId, setCategoryId] = useState("");
  const [tagIds, setTagIds] = useState([]);
  const [coverFile, setCoverFile] = useState(null);
  const [tags, setTags] = useState([]);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const [selectedLabels, setSelectedLabels] = useState([]);

  useEffect(() => {
    const fetchTags = async () => {
      try {
        const response = await storyService.getTags();
        const raw = response?.data?.data || response?.data || [];
        const list = Array.isArray(raw) ? raw : [];
        const normalized = list
          .filter((tag) => tag && tag.id != null)
          .map((tag) => ({
            value: String(tag.id),
            label: tag.name || String(tag.id),
          }));
        setTags(normalized);
      } catch (error) {
        console.error("getTags error", error);
        notify("Không tải được danh sách thể loại", "error");
      }
    };
    fetchTags();
  }, [notify]);

  useEffect(() => {
    const labelById = new Map(tags.map((t) => [String(t.value), t.label]));
    const combined = [];
    if (categoryId) {
      combined.push({
        id: String(categoryId),
        label: labelById.get(String(categoryId)) || String(categoryId),
        type: "category",
      });
    }
    for (const tagId of tagIds) {
      if (!tagId) continue;
      combined.push({
        id: String(tagId),
        label: labelById.get(String(tagId)) || String(tagId),
        type: "tag",
      });
    }
    const unique = [];
    const seen = new Set();
    for (const item of combined) {
      if (seen.has(item.id)) continue;
      seen.add(item.id);
      unique.push(item);
    }
    setSelectedLabels(unique);
  }, [categoryId, tagIds, tags]);

  const handleAddTag = (id) => {
    setTagIds((prev) => {
      if (prev.includes(id)) return prev;
      return [...prev, id];
    });
  };

  const handleRemoveTag = (id) => {
    setTagIds((prev) => prev.filter((item) => item !== id));
  };

  const validate = () => {
    const nextErrors = {};
    if (!title.trim()) nextErrors.title = "Tiêu đề là bắt buộc";
    if (!summary.trim()) nextErrors.summary = "Tóm tắt là bắt buộc";
    if (!categoryId) nextErrors.category = "Danh mục là bắt buộc";
    return nextErrors;
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    const nextErrors = validate();
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) return;
    try {
      setLoading(true);
      const toNumber = (value) => {
        const num = Number(value);
        return Number.isFinite(num) ? num : null;
      };
      const payload = {
        title: title.trim(),
        summary: summary.trim(),
        categoryId: toNumber(categoryId),
        tagIds: tagIds.map(toNumber).filter((id) => id != null),
        visibility,
      };
      const formData = new FormData();
      formData.append("data", JSON.stringify(payload));
      if (coverFile) {
        formData.append("cover", coverFile);
      }
      const response = await storyService.createStory(formData);
      const storyId = response?.data?.id || response?.data?.storyId;
      if (storyId) {
        notify("Tạo truyện thành công", "success");
        navigate(`/author/stories/${storyId}`);
      } else {
        notify("Tạo truyện thành công nhưng không có ID trả về", "info");
      }
    } catch (error) {
      console.error("createStory error", error);
      notify("Không thể tạo truyện. Vui lòng thử lại.", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page">
      <h2>Tạo truyện mới</h2>
      <form className="card form" onSubmit={handleSubmit}>
        <Input
          label="Tiêu đề"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          error={errors.title}
          placeholder="Nhập tiêu đề truyện"
        />
        <Input
          label="Tóm tắt"
          as="textarea"
          rows="4"
          value={summary}
          onChange={(e) => setSummary(e.target.value)}
          error={errors.summary}
          placeholder="Tóm tắt nội dung"
        />
        <FileUpload label="Ảnh bìa" onFileSelect={setCoverFile} />
        <Select
          label="Danh mục"
          options={tags}
          value={categoryId}
          onChange={setCategoryId}
          error={errors.category}
          placeholder="Chọn danh mục"
        />
        <div className="field">
          <span className="field-label">Thể loại</span>
          <div
            className="segment-ids"
            style={{ gap: "10px", flexWrap: "wrap" }}
          >
            {tags.map((tag) => (
              <button
                key={tag.value}
                type="button"
                className="chip"
                onClick={() => handleAddTag(String(tag.value))}
                style={{
                  border:
                    tagIds.includes(String(tag.value))
                      ? "1px solid #b23a48"
                      : "1px solid var(--border)",
                  background: tagIds.includes(String(tag.value))
                    ? "#f9e4e7"
                    : "#f2e8dc",
                  cursor: "pointer",
                }}
              >
                {tag.label}
              </button>
            ))}
          </div>
          {tags.length === 0 && (
            <span className="field-hint">Chưa có thể loại.</span>
          )}
        </div>
        {selectedLabels.length > 0 && (
          <div className="field">
            <span className="field-label">Đã chọn</span>
            <div className="segment-ids">
              {selectedLabels.map((item) => (
                <span key={item.id} className="chip">
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                    style={{ marginRight: "6px" }}
                  >
                    <path
                      fill="currentColor"
                      d="M20.59 13.41L12 4.83V3h-2v2.83l-8.59 8.58a2 2 0 0 0 0 2.83l3.34 3.34a2 2 0 0 0 2.83 0L20.59 16.24a2 2 0 0 0 0-2.83ZM6.18 19.07 2.83 15.7 11 7.53l3.35 3.35-8.17 8.19ZM18.17 14.83l-2.83-2.83 1.42-1.42 2.83 2.83-1.42 1.42Z"
                    />
                  </svg>
                  {item.label}
                  {item.type === "tag" && (
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(item.id)}
                      style={{
                        marginLeft: "6px",
                        border: "none",
                        background: "transparent",
                        cursor: "pointer",
                        fontWeight: 700,
                      }}
                      aria-label={`Remove ${item.label}`}
                    >
                      ×
                    </button>
                  )}
                </span>
              ))}
            </div>
          </div>
        )}
        <div className="field">
          <span className="field-label">Hiển thị</span>
          <div className="radio-group">
            <label>
              <input
                type="radio"
                name="visibility"
                value="DRAFT"
                checked={visibility === "DRAFT"}
                onChange={(e) => setVisibility(e.target.value)}
              />
              Nháp
            </label>
            <label>
              <input
                type="radio"
                name="visibility"
                value="PUBLIC"
                checked={visibility === "PUBLIC"}
                onChange={(e) => setVisibility(e.target.value)}
              />
              Công khai
            </label>
          </div>
        </div>
        <div className="form-actions">
          <Button type="submit" loading={loading}>
            Tạo truyện
          </Button>
        </div>
      </form>
      <p className="field-hint">
        Ghi chú: Danh mục và thể loại được gửi dưới dạng tagIds theo backend.
      </p>
    </div>
  );
};

export default CreateStory;
