// THIS FILE GENERATED BY CodeX: frontend/src/pages/Author/StoryDetail.jsx
import React, { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Button from "../../components/Button";
import CreateVolume from "./CreateVolume";
import useNotify from "../../hooks/useNotify";
import storyService from "../../services/storyService";

const StoryDetail = () => {
  const { storyId } = useParams();
  const { notify } = useNotify();
  const [story, setStory] = useState(null);
  const [volumes, setVolumes] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showCreateVolume, setShowCreateVolume] = useState(false);

  const fetchStory = useCallback(async () => {
    try {
      setLoading(true);
      const response = await storyService.getStory(storyId);
      const data = response?.data || {};
      const list =
        data.volumes ||
        data.volumeList ||
        data.data?.volumes ||
        data.data?.volumeList ||
        [];
      setStory(data);
      setVolumes(Array.isArray(list) ? list : []);
    } catch (error) {
      console.error("getStory error", error);
      notify("Không tải được thông tin truyện", "error");
    } finally {
      setLoading(false);
    }
  }, [notify, storyId]);

  useEffect(() => {
    fetchStory();
  }, [fetchStory]);

  return (
    <div className="page">
      <div className="page-header">
        <h2>Chi tiết truyện</h2>
        <Button type="button" onClick={() => setShowCreateVolume((s) => !s)}>
          {showCreateVolume ? "Đóng" : "Tạo Volume"}
        </Button>
      </div>

      {loading && <p>Đang tải dữ liệu...</p>}

      {story && (
        <div className="card">
          <h3>{story.title}</h3>
          <p className="story-summary">{story.summary || story.summaryHtml || ""}</p>
          {story.coverUrl && (
            <img className="cover-image" src={story.coverUrl} alt={story.title} />
          )}
        </div>
      )}

      {showCreateVolume && (
        <CreateVolume
          storyId={storyId}
          onCreated={() => {
            setShowCreateVolume(false);
            fetchStory();
          }}
          onCancel={() => setShowCreateVolume(false)}
        />
      )}

      <div className="card">
        <h3>Danh sách Volume</h3>
        {volumes.length === 0 && <p>Chưa có volume nào.</p>}
        <ul className="list">
          {volumes.map((volume) => (
            <li key={volume.id || volume.volumeId} className="list-item">
              <div>
                <strong>{volume.title}</strong>
                {volume.sequenceIndex && (
                  <span className="meta"># {volume.sequenceIndex}</span>
                )}
              </div>
              <Link
                to={`/author/stories/${storyId}/volumes/${
                  volume.id || volume.volumeId
                }/create-chapter`}
              >
                Tạo Chapter
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default StoryDetail;
