// THIS FILE GENERATED BY CodeX: frontend/src/App.jsx
import React from "react";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import CreateStory from "./pages/Author/CreateStory";
import StoryDetail from "./pages/Author/StoryDetail";
import CreateChapter from "./pages/Author/CreateChapter";

const App = () => {
  return (
    <BrowserRouter>
      <div className="app">
        <Header />
        <main className="container">
          <Routes>
            <Route path="/" element={<Navigate to="/author/create-story" />} />
            <Route path="/author/create-story" element={<CreateStory />} />
            <Route path="/author/stories/:storyId" element={<StoryDetail />} />
            <Route
              path="/author/stories/:storyId/volumes/:volumeId/create-chapter"
              element={<CreateChapter />}
            />
            <Route path="*" element={<Navigate to="/author/create-story" />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </BrowserRouter>
  );
};

export default App;
